server.port: 8443

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-alias: localhost

spring.cloud.gateway.routes:

- id: product-composite
  uri: http://product-composite
  predicates:
  - Path=/product-composite/**

- id: oauth2-server
  uri: http://${app.auth-server}
  predicates:
  - Path=/oauth2/**
  filters:
    - PreserveHostHeader
    - SetRequestHeader=X-Forwarded-Proto, https
    - SetRequestHeader=X-Forwarded-Port, 8443

- id: oauth2-login
  uri: http://${app.auth-server}
  predicates:
  - Path=/login/**
  filters:
    - PreserveHostHeader
    - SetRequestHeader=X-Forwarded-Proto, https
    - SetRequestHeader=X-Forwarded-Port, 8443

- id: oauth2-error
  uri: http://${app.auth-server}
  predicates:
  - Path=/error/**
  filters:
    - PreserveHostHeader
    - SetRequestHeader=X-Forwarded-Proto, https
    - SetRequestHeader=X-Forwarded-Port, 8443

- id: product-composite-swagger-ui
  uri: http://product-composite
  predicates:
  - Path=/openapi/**

- id: product-composite-swagger-ui-webjars
  uri: http://product-composite
  predicates:
  - Path=/webjars/**

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

management:
  tracing:
    propagation:
      type:
        - w3c
        - b3
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        readiness:
          include: ping, healthcheckMicroservices

---
spring.config.activate.on-profile: prod

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN