server.port: 9999
server.forward-headers-strategy: framework

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: docker

server.port: 80

# auth server 는 DB 를 사용하지 않기 때문에 ping으로 변경
management.endpoint.health.group.readiness.include: ping

---
spring.config.activate.on-profile: prod

logging.level.root: WARN